In [2]:
import psycopg2
import pandas as pd
import hidden

pd.set_option('display.max_columns', 500)

sql_string = hidden.psycopg2(hidden.secrets())
print('PostgreSQL connection data taken from hidden.py')

# Make the connection and cursor
conn = psycopg2.connect(sql_string, connect_timeout=3)

PostgreSQL connection data taken from hidden.py

In [5]:
pd.read_sql_query('''
SELECT pair_id, candle_open_time, atr_diff, rsi, rsi_diff, trend_up, trend_up3, cs_ss
  FROM features
 WHERE rsi_diff IS NULL
''', conn)

,pair_id,candle_open_time,atr_diff,rsi,rsi_diff,trend_up,trend_up3,cs_ss
0,0,2021-07-15 19:00:00,-2.857143e-07,59.773698,None,False,True,False
1,0,2021-07-15 18:30:00,3.500000e-06,NaN,None,None,None,None
2,1,2021-07-15 18:30:00,5.057857e+00,NaN,None,None,None,None
3,0,2021-07-15 18:45:00,1.570000e-06,NaN,None,None,None,None
4,2,2021-07-15 18:45:00,-3.728571e-01,NaN,None,None,None,None
5,-3,2017-08-17 04:00:00,NaN,0.000000,None,None,None,False
6,-2,2017-08-17 04:00:00,NaN,0.000000,None,None,None,False
7,2,2021-07-15 18:30:00,-2.707143e-01,NaN,None,None,None,None
8,1,2021-07-15 18:45:00,-5.107143e+00,NaN,None,None,None,None
9,-1,2017-07-14 04:00:00,NaN,0.000000,None,None,None,False
10,1,2021-07-15 19:00:00,-5.892857e-01,37.767580,None,True,True,False
11,2,2021-07-15 19:00:00,-5.214286e-02,48.041750,None,False,True,False

# Old Checks:

In [3]:
feature_df = pd.read_sql_query('''
SELECT *
 FROM candlestick_15m as c,
 features as f
WHERE c.open_time = f.candle_open_time
  AND c.pair_id = f.pair_id
  AND c.pair_id = 0 --ETHBTC
  AND c.open_time between '2018-01-01' and '2021-01-01'
--LIMIT 100
''', conn)
feature_df.drop(columns='candle_open_time', inplace=True)
feature_df.head()

,pair_id,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,created_at,updated_at,pair_id,open_1,high_1,low_1,close_1,open_2,high_2,low_2,close_2,open_3,high_3,low_3,close_3,ma14,ma30,ma90,atr,atr_diff,atr_ma14,open_4,high_4,low_4,close_4,open_5,high_5,low_5,close_5,open_6,high_6,low_6,close_6,open_7,high_7,low_7,close_7,open_8,high_8,low_8,close_8,open_9,high_9,low_9,close_9,open_10,high_10,low_10,close_10,open_11,high_11,low_11,close_11,open_12,high_12,low_12,close_12,open_13,high_13,low_13,close_13,open_14,high_14,low_14,close_14,ema_up,ema_down,rsi,rsi_diff,rsi_ma14
0,0,2018-01-02 07:15:00,0.063846,0.063985,0.063723,0.063799,2765.072,2018-01-02 07:29:59.999,176.582059,3888,1328.316,84.860509,2021-06-30 14:24:31.900306+00:00,2021-07-01 10:57:33.052002+00:00,0,0.063941,0.063999,0.063663,0.063846,0.064235,0.064297,0.063937,0.063941,0.064667,0.064667,0.064096,0.064235,0.063992,0.062278,0.058292,0.000683,-0.000068,0.001257,0.064613,0.064879,0.064537,0.064667,0.064101,0.065125,0.064046,0.064611,0.064086,0.064210,0.063802,0.064101,0.064397,0.064397,0.063869,0.064056,0.064770,0.065500,0.064100,0.064326,0.063591,0.064988,0.063525,0.064770,0.063658,0.063742,0.063508,0.063565,0.063550,0.063822,0.063230,0.063595,0.062902,0.063704,0.062712,0.063535,0.062041,0.062923,0.061932,0.062839,0.063080,0.063150,0.061932,0.061941,0.000272,0.000179,60.316948,-0.451651,65.667244
1,0,2018-01-03 16:00:00,0.058265,0.058320,0.057610,0.057687,5952.707,2018-01-03 16:14:59.999,345.455334,9048,2949.672,171.233583,2021-06-30 14:24:31.900306+00:00,2021-07-01 10:57:33.052002+00:00,0,0.058481,0.058600,0.058252,0.058321,0.058425,0.058622,0.058311,0.058481,0.058440,0.058760,0.058338,0.058400,0.058428,0.058448,0.058113,0.000408,0.000009,0.000423,0.058541,0.058698,0.058248,0.058366,0.058572,0.058707,0.058349,0.058541,0.058323,0.058726,0.058002,0.058569,0.058495,0.058630,0.058229,0.058323,0.058410,0.058626,0.058360,0.058494,0.058476,0.058537,0.058231,0.058410,0.058584,0.058654,0.058290,0.058476,0.058687,0.058750,0.058508,0.058584,0.058708,0.058779,0.058441,0.058630,0.058372,0.058839,0.058372,0.058710,0.058510,0.058800,0.058211,0.058384,0.000070,0.000122,36.416818,-11.296406,50.414898
2,0,2018-01-04 20:00:00,0.063682,0.065345,0.062655,0.063001,6620.656,2018-01-04 20:14:59.999,420.947125,10058,2774.923,176.597564,2021-06-30 14:24:31.900306+00:00,2021-07-01 10:57:33.052002+00:00,0,0.064606,0.064911,0.063218,0.063650,0.064749,0.064980,0.064250,0.064719,0.064836,0.065569,0.064522,0.064651,0.066146,0.067146,0.064370,0.001337,0.000117,0.001150,0.065525,0.066131,0.064507,0.064776,0.065777,0.066105,0.065229,0.065525,0.066422,0.066669,0.065602,0.065764,0.066756,0.066949,0.066057,0.066401,0.067374,0.068400,0.066500,0.066720,0.067916,0.068317,0.066978,0.067374,0.068224,0.068400,0.067029,0.067986,0.068513,0.069566,0.068138,0.068156,0.068860,0.069378,0.068265,0.068537,0.068823,0.069552,0.068600,0.068784,0.068852,0.069549,0.068500,0.068823,0.000095,0.000335,21.981585,-2.656192,42.045110
3,0,2018-01-05 21:30:00,0.057083,0.057200,0.055848,0.055992,5970.453,2018-01-05 21:44:59.999,336.636505,7287,3162.645,178.382339,2021-06-30 14:24:31.900306+00:00,2021-07-01 10:57:33.052002+00:00,0,0.057207,0.057943,0.056663,0.057056,0.058260,0.058357,0.056595,0.057207,0.059764,0.059929,0.058100,0.058108,0.058174,0.058631,0.062745,0.001468,0.000036,0.001418,0.059590,0.060300,0.059398,0.059784,0.058982,0.059889,0.058976,0.059590,0.058557,0.058999,0.058200,0.058983,0.057844,0.058940,0.055110,0.058499,0.059221,0.059221,0.057802,0.057900,0.059771,0.060599,0.059023,0.059222,0.058178,0.059799,0.058139,0.059643,0.057501,0.058279,0.057501,0.058177,0.056420,0.058082,0.056250,0.057860,0.056487,0.056514,0.055900,0.056420,0.056746,0.056955,0.056100,0.056398,0.000246,0.000454,35.136417,-4.284768,43.599227
4,0,2018-01-05 22:00:00,0.056588,0.057600,0.055928,0.056256,5112.336,2018-01-05 22:14:59.999,290.245366,7084,2751.716,156.224873,2021-06-30 14:24:31.900306+00:00,2021-07-01 10:57:33.052002+00:00,0,0.055986,0.056992,0.055708,0.056586,0.057083,0.057200,0.055848,0.055992,0.057207,0.057943,0.056663,0.057056,0.058072,0.058339,0.062593,0.001504,-0.000011,0.001449,0.058260,0.058357,0.056595,0.057207,0.059764,0.059929,0.058100,0.058108,0.059590,0.060300,0.059398,0.059784,0.058982,0.059889,0.058976,0.059590,0.058557,0.058999,0.058200,0.058983,0.057844,0.058940,0.055110,0.058499,0.059221,0.059221,0.057802,0.057900,0.059771,0.060599,0.059023,0.059222,0.058178,0.059799,0.058139,0.059643,0.057501,0.058279,0.057501,0.058177,0.056420,0.058082,0.056250,0.057860,0.000251,0.000415,37.730428,-1.384650,44.305174

In [4]:
feature_df.shape

(104797, 82)

In [5]:
suffix='20210715'
compare_df = pd.read_pickle(f'../data/X_{suffix}.pkl').reset_index()
compare_df.head()

,open_time,open,high,low,close,volume,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,open_1,high_1,low_1,close_1,open_2,high_2,low_2,close_2,open_3,high_3,low_3,close_3,ma14,ma30,ma90,atr,atr_diff,atr_ma14,rsi,rsi_diff,rsi_ma14,res14,sup14,res14_1,sup14_1,res14_2,sup14_2,res14_3,sup14_3,res30,sup30,res30_1,sup30_1,res30_2,sup30_2,res30_3,sup30_3,res90,sup90,res90_1,sup90_1,res90_2,sup90_2,res90_3,sup90_3,trend_up,trend_up3,trend_up14,trend_up30,cs_ss,cs_ssR,cs_hm,cs_hmR,cs_brh,cs_buh,cs_ebu,cs_ebr,cs_ss_1,cs_ssR_1,cs_hm_1,cs_hmR_1,cs_brh_1,cs_buh_1,cs_ebu_1,cs_ebr_1
0,2017-07-14 04:00:00,0.080000,0.086400,0.080000,0.086400,8.752,0.728274,26,3.268,0.282355,0.080000,0.08640,0.080000,0.086400,0.080000,0.08640,0.080000,0.086400,0.080000,0.0864,0.080000,0.086400,0.086400,0.086400,0.086400,0.006400,0.000000,0.006400,0.000000,0.000000,0.000000,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,2017-07-14 04:15:00,0.085289,0.086000,0.085128,0.085811,61.042,5.217079,33,2.738,0.235027,0.080000,0.08640,0.080000,0.086400,0.080000,0.08640,0.080000,0.086400,0.080000,0.0864,0.080000,0.086400,0.086106,0.086106,0.086106,0.003836,-0.002564,0.005118,0.000000,0.000000,0.000000,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,2017-07-14 04:30:00,0.085811,0.086380,0.085811,0.086314,53.769,4.631740,41,21.225,1.829643,0.085289,0.08600,0.085128,0.085811,0.080000,0.08640,0.080000,0.086400,0.080000,0.0864,0.080000,0.086400,0.086175,0.086175,0.086175,0.002747,-0.001089,0.004328,6.164216,6.164216,2.054739,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,2017-07-14 04:45:00,0.086314,0.086380,0.086309,0.086347,42.818,3.697253,61,7.948,0.686295,0.085811,0.08638,0.085811,0.086314,0.085289,0.08600,0.085128,0.085811,0.080000,0.0864,0.080000,0.086400,0.086218,0.086218,0.086218,0.002078,-0.000669,0.003765,6.571117,0.406902,3.183833,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,True,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,2017-07-14 05:00:00,0.085874,0.086205,0.084608,0.084680,16.520,1.404228,15,1.176,0.100914,0.086314,0.08638,0.086309,0.086347,0.085811,0.08638,0.085811,0.086314,0.085289,0.0860,0.085128,0.085811,0.085910,0.085910,0.085910,0.002010,-0.000068,0.003414,5.316869,-1.254248,3.610441,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,0.0864,0.08,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

# Check Column Differences

In [6]:
# Column comparison
ignore_columns = ['pair_id','open_time','open','high','low','close','volume','quote_asset_volume',
                  'number_of_trades','taker_buy_base_asset_volume','taker_buy_quote_asset_volume',
                  'close_time','created_at','updated_at'
                 ]

for col in feature_df.columns:
    if col not in ignore_columns:
        if col not in compare_df.columns:
            print(f'Additional column in features: {col}')
for col in compare_df.columns:
    if col not in ignore_columns:
        if col not in feature_df.columns:
            print(f'Missing column in features: {col}')

Additional column in features: open_4
Additional column in features: high_4
Additional column in features: low_4
Additional column in features: close_4
Additional column in features: open_5
Additional column in features: high_5
Additional column in features: low_5
Additional column in features: close_5
Additional column in features: open_6
Additional column in features: high_6
Additional column in features: low_6
Additional column in features: close_6
Additional column in features: open_7
Additional column in features: high_7
Additional column in features: low_7
Additional column in features: close_7
Additional column in features: open_8
Additional column in features: high_8
Additional column in features: low_8
Additional column in features: close_8
Additional column in features: open_9
Additional column in features: high_9
Additional column in features: low_9
Additional column in features: close_9
Additional column in features: open_10
Additional column in features: high_10
Additional column in features: low_10
Additional column in features: close_10
Additional column in features: open_11
Additional column in features: high_11
Additional column in features: low_11
Additional column in features: close_11
Additional column in features: open_12
Additional column in features: high_12
Additional column in features: low_12
Additional column in features: close_12
Additional column in features: open_13
Additional column in features: high_13
Additional column in features: low_13
Additional column in features: close_13
Additional column in features: open_14
Additional column in features: high_14
Additional column in features: low_14
Additional column in features: close_14
Additional column in features: ema_up
Additional column in features: ema_down
Missing column in features: res14
Missing column in features: sup14
Missing column in features: res14_1
Missing column in features: sup14_1
Missing column in features: res14_2
Missing column in features: sup14_2
Missing column in features: res14_3
Missing column in features: sup14_3
Missing column in features: res30
Missing column in features: sup30
Missing column in features: res30_1
Missing column in features: sup30_1
Missing column in features: res30_2
Missing column in features: sup30_2
Missing column in features: res30_3
Missing column in features: sup30_3
Missing column in features: res90
Missing column in features: sup90
Missing column in features: res90_1
Missing column in features: sup90_1
Missing column in features: res90_2
Missing column in features: sup90_2
Missing column in features: res90_3
Missing column in features: sup90_3
Missing column in features: trend_up
Missing column in features: trend_up3
Missing column in features: trend_up14
Missing column in features: trend_up30
Missing column in features: cs_ss
Missing column in features: cs_ssR
Missing column in features: cs_hm
Missing column in features: cs_hmR
Missing column in features: cs_brh
Missing column in features: cs_buh
Missing column in features: cs_ebu
Missing column in features: cs_ebr
Missing column in features: cs_ss_1
Missing column in features: cs_ssR_1
Missing column in features: cs_hm_1
Missing column in features: cs_hmR_1
Missing column in features: cs_brh_1
Missing column in features: cs_buh_1
Missing column in features: cs_ebu_1
Missing column in features: cs_ebr_1

# Check Value Differences

In [7]:
# Value comparison
import numpy as np

merged_df = feature_df.merge(compare_df, how='left', left_on='open_time', right_on='open_time')
check_cols = [col[:-2]for col in merged_df.columns if col.endswith('_x')]

for col in check_cols:
    if any(~np.isclose(merged_df[f'{col}_x'], merged_df[f'{col}_y'])):
        percent = (merged_df[f'{col}_x'] != merged_df[f'{col}_y']).sum() / len(merged_df)
        difference = np.mean(abs(merged_df[f'{col}_x'] - merged_df[f'{col}_y']))
        example = merged_df[merged_df[f'{col}_x'] != merged_df[f'{col}_y']].sample(1)[['open_time', f'{col}_x',f'{col}_y']].values
        print(f'Column {col} is off on {percent} of values by a mean difference of {difference}')
        print(f'  Example = {example}\n')

# Issue with ATR

In [19]:
display_cols = ['open_time','open','close','high','low','open_1','close_1','high_1','low_1','atr']
display(feature_df[feature_df.open_time == '2018-07-14 18:45:00'][display_cols])
display(compare_df[compare_df.open_time == '2018-07-14 18:45:00'][display_cols])

,open_time,open,close,high,low,open_1,close_1,high_1,low_1,atr
25464,2018-07-14 18:45:00,0.069405,0.069434,0.069501,0.06939,0.069473,0.069393,0.069521,0.06936,0.000176

,open_time,open,close,high,low,open_1,close_1,high_1,low_1,atr
34888,2018-07-14 18:45:00,0.069405,0.069434,0.069501,0.06939,0.069473,0.069393,0.069521,0.06936,0.000176

In [22]:
def calculate_atr(df, period=14):
    '''
    Calculate the Average True Range (ATR)
    '''
    df2=df[['high','low','close','close_1']].copy()
    df2['tr'] = np.max([df2.high, df2.close_1], axis=0) - np.min([df2.low, df2.close_1], axis=0)
    df2['atr'] = df2.tr.rolling(period).mean()
    return df2[['high','close_1','low','tr','atr']]

calculate_atr(feature_df.loc[59-13:59].set_index('open_time')) #.iloc[-1:]

                         high   close_1       low        tr       atr
open_time
2017-07-14 15:30:00  0.087170  0.086898  0.087170  0.000272       NaN
2017-07-14 15:45:00  0.086788  0.087170  0.086288  0.000882       NaN
2017-07-14 16:00:00  0.086556  0.086288  0.085999  0.000557       NaN
2017-07-14 16:15:00  0.086100  0.086251  0.085477  0.000774       NaN
2017-07-14 16:30:00  0.086751  0.085850  0.085850  0.000901       NaN
2017-07-14 16:45:00  0.086780  0.086557  0.086347  0.000433       NaN
2017-07-14 17:00:00  0.086720  0.086780  0.086347  0.000433       NaN
2017-07-14 17:15:00  0.086762  0.086720  0.085850  0.000912       NaN
2017-07-14 17:30:00  0.086187  0.086009  0.086009  0.000178       NaN
2017-07-14 17:45:00  0.086277  0.086120  0.086009  0.000268       NaN
2017-07-14 18:00:00  0.086075  0.086075  0.086075  0.000000       NaN
2017-07-14 18:15:00  0.086345  0.086075  0.086075  0.000270       NaN
2017-07-14 18:30:00  0.087836  0.086345  0.087836  0.001491       NaN
2017-07-14 18:45:00  0.087836  0.087836  0.087836  0.000000  0.000526